version: "3.7"

networks:
  LOCAL_NET:
    driver: bridge

services:

  MYSQL_DATABASE:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    restart: always
    networks:
      - LOCAL_NET

  CATEGORIA_API:
    image: ulissesmb/categoria-web:0.0.1
    restart: on-failure
    depends_on:
      - MYSQL_DATABASE
    ports:
      - '8080:8088'
    environment:
      - DB_HOST=MYSQL_DATABASE:3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=teste
    networks:
      - LOCAL_NET

  WEB:
    image: ulissesmb/web:0.0.1
    ports:
      - '80:80'
    restart: always
    depends_on:
      - CATEGORIA_API
    networks:
      - LOCAL_NET